CONFIG_ZMK_USB=n # ZMK_USB is only allowed when: not split or, split and role is central (i.e., not right_dongle)

## PMW3360 Driver
## https://github.com/george-norton/zmk-driver-pmw3360
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_PIXART_PMW3360=y
CONFIG_ZMK_POINTING=y
#CONFIG_SPI_LOG_LEVEL_DBG=y
